### ISSUE TITLE
Bug in TreePickerHelper shows "manager" in every popup

### ISSUE THREAD

**Issue by Total-Reality** [codefog/contao-widget_tree_picker#11]
Hi, there is a bug in Version 2.0.1
TreePickerHelper.php line 121:

The settings show the manager in every popup in Contao Backend, e.g. in contao/main.php?do=news -> click on the blue info button. This shows a link "Zurück zur Auswahl" under the main_headline. It is very confusing

**Comment by qzminski** [comment]
Can you send me a screenshot please? Are you using the extension alongside with news_categories or what is your current setup? What is your Contao version?

**Comment by Total-Reality** [comment]
Yeah news_categories. Contao 3.5.4
It is on every backend page e.g. member or news. Just click on the blue info/show button in the operations and you will see it

**Comment by qzminski** [comment]
There is a problem indeed, however I am not sure yet how to fix it. Any ideas are very welcome.

**Comment by Total-Reality** [comment]
You can solve it e.g. in this way:

1. system\modules\widget_tree_picker\classes\TreePickerHelper.php
line 123

Before:
``if (\Input::get('popup') && $objTemplate->getName() == 'be_main' && \Input::get('do') != 'page' && \Input::get('do') != 'files' && $this->Session->get('treePickerRef'))

After:
``if (\Input::get('popup') && $objTemplate->getName() == 'be_main' && \Input::get('edit') && $this->Session->get('treePickerRef'))

2. system\modules\widget_tree_picker\public\treepicker.php
line 124

Before:
``$this->Template->managerHref = 'contao/main.php?' . ampersand($objTreeSelector->managerHref) . '&amp;popup=1';

After:
``$this->Template->managerHref = 'contao/main.php?' . ampersand($objTreeSelector->managerHref) . '&amp;popup=1&amp;edit=true';

**Comment by qzminski** [comment]
Fixed in d171d6d.
