### ISSUE TITLE
Several Errors with news_categories

### ISSUE THREAD

**Issue by rustykowski** [codefog/contao-widget_tree_picker#12]
![bildschirmfoto 2016-07-16 um 12 57 36](https://cloud.githubusercontent.com/assets/1775048/16894378/ef47db6a-4b54-11e6-90ef-2b4bafc6bf8c.png)

The Cetegory-Picker from News-Categrories is showing up like this. No selection possible.
There are errors in the console and in the error-log, but I am not able to see the real cause. Do you have an idea?

**Console:**
Uncaught SyntaxError: Unexpected token <
in /system/modules/widget_tree_picker/public/treepicker.php/assets/js/a94bfa453d23.js:1
Uncaught ReferenceError: Locale is not defined
in /system/modules/widget_tree_picker/public/treepicker.php:17
Uncaught SyntaxError: Unexpected token <
in /system/modules/widget_tree_picker/public/treepicker.php/system/modules/widget_tree_picker/assets/treepicker.min.js:1
Uncaught ReferenceError: Theme is not defined
in /system/modules/widget_tree_picker/public/treepicker.php:40

**Error-Log:**
PHP Fatal error: Uncaught exception 'Exception' with message 'The table name must not be empty' thrown in /html/contao/system/modules/core/library/Contao/DcaLoader.php on line 48
#0 /html/contao/system/modules/core/library/Contao/Controller.php(1297): Contao\DcaLoader->__construct(NULL)
#1 /html/contao/system/modules/widget_tree_picker/public/treepicker.php(97): Contao\Controller::loadDataContainer(NULL)
#2 /html/contao/system/modules/widget_tree_picker/public/treepicker.php(141): TreePicker\TreePicker->run()

Contao 3.5.11
widget_tree_picker 2.3.0
news_categories 2.7.2
Installation via ER2 and also manually

**Comment by qzminski** [comment]
Are you sure you have rebuilt your internal cache? It looks like there is something wrong with the path as this ```system/modules/widget_tree_picker/public/treepicker.php/assets/js/a94bfa453d23.js``` should be in fact this ```assets/js/a94bfa453d23.js```. Do you experience other Contao issues on the same system?

**Comment by rustykowski** [comment]
Yes, i rebuilt the cache, and no – no other Contao issues :-|
I will run the contao check next.

**Comment by qzminski** [comment]
Are there any other 3rd party extensions installed?

Can you right-click on the ```Change selection``` button of the widget and copy its URL and paste it here?

**Comment by rustykowski** [comment]
Hello Kamil,
I disabled the other extensions (just backup_db and easy_themes) but with no change of behaviour.
The href of the button is contao/main.php?do=news&table=tl_news_category&popup=1&wtp=1
That's correct, isn't it?

**Comment by qzminski** [comment]
No, the target URL of the button should be something like:

```
system/modules/widget_tree_picker/public/treepicker.php?do=news&table=tl_news&field=categories&act=show&id=8&value=2,3,17&rt=c7c6d5ceb64e402c2d1db096beaf2659
```

Are we talking about the same button?

![2016-07-18 at 08 40](https://cloud.githubusercontent.com/assets/193483/16907358/583e72a4-4cc3-11e6-83f7-ea659da733b2.png)

**Comment by rustykowski** [comment]
Sorry, here is target of the that button:
`system/modules/widget_tree_picker/public/treepicker.php?do=news&table=tl_news&field=categories&act=show&id=5&value=&rt=a8103d0a5ced8cf28a9e46d88eff6748`
Thank you fpr your efforts!

**Comment by qzminski** [comment]
Hmm that looks good to me. Do you have that Contao instance online so I could check directly on your server what's going on?

**Comment by rustykowski** [comment]
Frontend:
http://p355631.mittwaldserver.info/
Backend -> E-Mail

**Comment by qzminski** [comment]
For some reason there was the ```system/config/pathconfig.php``` missing in your installation. I have added it and now everything works like a charm.

**Comment by rustykowski** [comment]
Thanks a lot for your investigation!
