### ISSUE TITLE
Problem with migration

### ISSUE THREAD

**Issue by Vinny38** [codefog/contao-widget_tree_picker#13]
Hi
I got a Php error (see below) while trying to migrate my local Contao installation to live server.
If I understand well, it seems to be a problem with Tree picker extension.
I  downgraded my Contao version to 3.5.13 in order to make sure WTP 2.3.0 is compliant, but it still doesn't work properly.
Please note I need this widget cause I want to use the News Category extension.
I managed to migrate my installation deleting both News Category and Tree Picker from local and reinstalling them from live, but I obviously lost all my settings...
Here's the error log i got when trying to launch the contao/install.php tool:
any idea?
Thanks in advance

```
Warning: mysqli::real_connect(): (28000/1045): Access denied for user 'root'@'localhost' (using password: NO) in system/modules/core/library/Contao/Database/Mysqli.php on line 46
#0 [internal function]: __error(2, 'mysqli::real_co...', '/home/www/clien...', 46, Array)
#1 system/modules/core/library/Contao/Database/Mysqli.php(46): mysqli->real_connect('localhost', 'root', '', 'database', 3306, '')
#2 system/modules/core/library/Contao/Database.php(81): Contao\Database\Mysqli->connect()
#3 system/modules/core/library/Contao/Database.php(165): Contao\Database->__construct(Array)
#4 [internal function]: Contao\Database::getInstance()
#5 system/modules/core/library/Contao/System.php(140): call_user_func(Array)
#6 system/modules/core/classes/Backend.php(30): Contao\System->import('Database')
#7 system/modules/core/library/Contao/System.php(140): Contao\Backend->__construct()
#8 system/modules/core/library/Contao/Template.php(272): Contao\System->import('TreePicker\\Tree...')
#9 system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
#10 system/modules/core/classes/BackendTemplate.php(107): Contao\BackendTemplate->parse()
#11 system/modules/core/controllers/BackendInstall.php(878): Contao\BackendTemplate->output()
#12 system/modules/core/controllers/BackendInstall.php(107): Contao\BackendInstall->outputAndExit()
#13 contao/install.php(24): Contao\BackendInstall->run()
#14 {main}

Fatal error: Uncaught exception Exception with message Access denied for user 'root'@'localhost' (using password: NO) thrown in system/modules/core/library/Contao/Database/Mysqli.php on line 50
#0 system/modules/core/library/Contao/Database.php(81): Contao\Database\Mysqli->connect()
#1 system/modules/core/library/Contao/Database.php(165): Contao\Database->__construct(Array)
#2 [internal function]: Contao\Database::getInstance()
#3 system/modules/core/library/Contao/System.php(140): call_user_func(Array)
#4 system/modules/core/classes/Backend.php(30): Contao\System->import('Database')
#5 system/modules/core/library/Contao/System.php(140): Contao\Backend->__construct()
#6 system/modules/core/library/Contao/Template.php(272): Contao\System->import('TreePicker\\Tree...')
#7 system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
#8 system/modules/core/classes/BackendTemplate.php(107): Contao\BackendTemplate->parse()
#9 system/modules/core/controllers/BackendInstall.php(878): Contao\BackendTemplate->output()
#10 system/modules/core/controllers/BackendInstall.php(107): Contao\BackendInstall->outputAndExit()
#11 contao/install.php(24): Contao\BackendInstall->run()
#12 {main}
```

**Comment by qzminski** [comment]
You have no connection to the database:

```
Fatal error: Uncaught exception Exception with message Access denied for user 'root'@'localhost' (using password: NO) thrown in system/modules/core/library/Contao/Database/Mysqli.php on line 50
```

**Comment by Vinny38** [comment]
Hi Kamil,
thanks for your fast answer.
However, how do you explain I can launch the install tool without the WTP extension? 
There seems to be a connection problem with database only when WTP is installed (see #8)
cheers

**Comment by qzminski** [comment]
If that's caused by the extension then it would also not work on your localhost before the migration, no? The message says you are trying to connect to the database with the ```root``` user. Does it correspond with your ```system/config/localconfig.php``` setup?

How is #8 related to this?

**Comment by Vinny38** [comment]
Kamil, 
root user obviously relates to my local apache server.
as far as I understand the install tool, it allows to setup the connection with live Mysql database. This is the way I always used with my Contao projects. 
I made that test:
installed a brand new contao installation. Move it to live server -> Install tool works
install News categories (and tree-picker) extension to my localhost. Move it to live server -> php error
#8 system/modules/core/library/Contao/Template.php(272): Contao\System->import('**TreePicker\\Tree...**')
Now, I don't want to waste your precious time.
What I do to make things work is that I manually setup my localconfig.php with live server settings. Not the best way, but it does work.
Thanks for your time
Vinny
