### ISSUE TITLE
Errors: Undefined array key

### ISSUE THREAD

**Issue by operatorone** [codefog/contao-widget_tree_picker#17]
Hi, I just updated a Contao to 4.13.6 on PHP 8.0.16 and an extension which I use also uses the contao-widget_tree_picker.

I got some errors in the backend and tried to fix them:

`Warning: Trying to access array offset on value of type null in /home/www/contao_update/vendor/codefog/contao-widget_tree_picker/classes/TreePickerHelper.php on line 76
Warning: Undefined array key "breadcrumb" in /home/www/contao_update/vendor/codefog/contao-widget_tree_picker/public/treepicker.php on line 122
Warning: Undefined array key "encrypt" in /home/www/contao_update/vendor/codefog/contao-widget_tree_picker/classes/TreePickerHelper.php on line 50
Warning: Undefined array key "flag" in /home/www/contao_update/vendor/codefog/contao-widget_tree_picker/classes/TreePickerHelper.php on line 66
Warning: Undefined array key "maxCharacters" in /home/www/contao_update/vendor/codefog/contao-widget_tree_picker/classes/TreePickerHelper.php on line 83
Warning: Undefined array key "parentsUnselectable" in /home/www/contao_update/vendor/codefog/contao-widget_tree_picker/widgets/WidgetTreeSelector.php on line 426
Warning: Undefined array key "reference" in /home/www/contao_update/vendor/codefog/contao-widget_tree_picker/classes/TreePickerHelper.php on line 76
Warning: Undefined array key "rootNodes" in /home/www/contao_update/vendor/codefog/contao-widget_tree_picker/widgets/WidgetTreeSelector.php on line 233
Warning: Undefined array key "selectParents" in /home/www/contao_update/vendor/codefog/contao-widget_tree_picker/widgets/WidgetTreeSelector.php on line 426
Warning: Undefined array key "sp_filter_product" in /home/www/contao_update/vendor/fast-media/contao-simple-products-extended/dca/tl_product.php on line 472
Warning: Undefined array key 6 in /home/www/contao_update/vendor/codefog/contao-widget_tree_picker/widgets/WidgetTreeSelector.php on line 389
Warning: Undefined array key 15 in /home/www/contao_update/vendor/codefog/contao-widget_tree_picker/widgets/WidgetTreeSelector.php on line 389
`

The only error I couldn't fix was the last one:

`Warning: Undefined array key 15 in /home/www/contao_update/vendor/codefog/contao-widget_tree_picker/widgets/WidgetTreeSelector.php on line 389`

May be you can use my fixes and can help me with the last one?

[widget_tree_picker_fixes.zip](https://github.com/codefog/contao-widget_tree_picker/files/9055967/widget_tree_picker_fixes.zip)

**Comment by qzminski** [comment]
I have just released 2.4.2 which should fix the errors. Please note that this extension is deprecated and no longer maintained. The extension you are using should implement the Contao picker features.
