### ISSUE TITLE
incompatible with Contao 3.2

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-widget_tree_picker#7]
The change from #4 made the extension incompatible with older Contao versions. The line
```js
var inp = frm.document.getElementById('tl_select').getElementsByTagName('input');
```
causes 
```
TypeError: h.document.getElementById(...) is null
```
under Contao 3.2 when trying to select and apply a category from the extension [codefog/contao-news_categories](https://github.com/codefog/contao-news_categories), since there is no HTML Element with the ID `tl_select` in the iframe of the tree selector.

This is because under Contao 3.5 the HTML element has the ID `tl_select` while in Contao 3.2 for instance the HTML element has the ID `tl_listing`.

**Comment by fritzmg** [comment]
Ah, I see where the problem is now. Tag __2.0.0__ still had
```
"contao/core": ">=3.2"
```
In its [composer.json](https://github.com/codefog/contao-widget_tree_picker/blob/2.0.0/composer.json), that's the actual problem. You should remove this tag from the repository, or update the composer.json within this tag, otherwise 2.0.0 can be installed via composer on Contao < 3.5 as well - which isn't compatible.

**Comment by fritzmg** [comment]
In the mean time I have fixed this by manually adding
```
"codefog/contao-widget_tree_picker": "1.*"
```
to the `composer.json`

**Comment by qzminski** [comment]
Please use version 2.5.1 that was released today.

**Comment by fritzmg** [comment]
Yeah, version 2.5.1 of `news_categories` includes
```
"codefog/contao-widget_tree_picker": ">=1.0.5,<2.0"
```
in its composer.json. However, this does not fix the original problem. Any extension that does not specifically require a version under 2.0.0 (or if you just use the extension for your own purposes) will cause this problem, since composer will allow the installation of `codefog/contao-widget_tree_picker` in Contao versions under 3.5.

This is not invalid ;). The tag 2.0.0 should be removed from packagist, so that it cannot be erroneously installed in the wrong Contao version. Likewise you can remove tag 2.0.0 and re-tag it again with the correct composer.json - but since there is no other difference between tag 2.0.0 and 2.0.1, tag 2.0.0 could simply be removed from the repository as well.

**Comment by aschempp** [comment]
I think that is actually a problem in the extension. If everyone is using semantic versioning (and you should when using Composer), an extension should never already be marked as compatible with version 2.0.0.

**Comment by qzminski** [comment]
I think changing history is not a good idea. Just please use the 2.0.1 version for Contao 3.5 and I will update news_categories composer file.

**Comment by fritzmg** [comment]
@aschempp: No, the actual problem is within `widget_tree_picker` itself. As already said:

* version `2.0.0` of the `widget_tree_picker` extension is (deliberately) incompatible with any Contao version lower than 3.5 (see the change made for #4)
* however, when the [release tag 2.0.0](https://github.com/codefog/contao-widget_tree_picker/tree/2.0.0) was created, the [composer.json](https://github.com/codefog/contao-widget_tree_picker/blob/2.0.0/composer.json) has not been updated to reflect this change and this still contains `"contao/core": ">=3.2"` instead of `"contao/core": "3.5.*"
* to fix this, a new [release tag 2.0.1](https://github.com/codefog/contao-widget_tree_picker/tree/2.0.1) was created with the updated composer.json. See 6be06915f16d8b497f7f4e69a3f761516839b8ae
* however, since the release tag `2.0.0` still exists in the repository and on packagist, composer might install version `2.0.0` in your Contao < 3.5 installation, even though it is not compatible with that Contao version, if you do not manually restrict it (regardless if this happens in the `composer.json` of an extension or your own `composer.json`)

Currently, if you develop your own extensions and want to use `widget_tree_picker` you have to be careful about your `require` statement in your `composer.json` and thus it also becomes more difficult to provide single releases of your own extension for multiple Contao versions.

**Comment by Toflar** [comment]
That's simply wrong. You **never ever** change history or tags. That would make the whole point about versioning and tagging completely pointless. @qzminski did the correct thing: releasing a new version that fixes the bug. You simply have to require `>=2.0.1` or `>=2.0.1,<3.0` (or `^2.0.1` which is the same as  `>=2.0.1,<3.0`) if `2.0.0` is broken or does not work with your extension.

By the way:

> Currently, if you develop your own extension and want to use widget_tree_picker you have to be careful about your require statement in your composer.json[...]

You always have to be careful about your require statements? Why should that be an argument?

By the way 2:

> As it stands currently, version 2.0.0 is a "broken" release.

Yes, and a broken release is everything that contains bugs. No matter if the bug is in the code or the dependency definition in `composer.json`.

**Comment by fritzmg** [comment]
> You never ever change history or tags

I agree, but as I said, removing it from packagist would suffice. I don't know what the usual course of action is here.

Currently you simply cannot do something like this in a release of your own extension:
```
"contao/core": ">=3.2,<3.6",
"codefog/contao-widget_tree_picker": ">=1.0.5"
```
Since this will result in a broken installation under Contao 3.2 through 3.4.

Neither can you do this:
```
"contao/core": ">=3.2,<3.6",
"codefog/contao-widget_tree_picker": "<2"
```
Since this makes it impossible to install your extension under Contao 3.5.

The version `2.0.0` release of `widget_tree_picker` forces you to always provide two different releases for your own extension, if your extension happens to support multiple Contao versions and uses `widget_tree_picker`.
```
"contao/core": ">=3.2,<3.5",
"codefog/contao-widget_tree_picker": "1.*"
```
```
"contao/core": "3.5.*",
"codefog/contao-widget_tree_picker": ">=2.*,<3"
```

**Comment by Toflar** [comment]
> Currently you simply cannot do something like this in a release of your own extension:
> ```
> "contao/core": ">=3.2,<3.6",
> "codefog/contao-widget_tree_picker": ">=1.0.5"
> ```

Yes you can:

```json
"require": {
    "contao/core": ">=3.2,<3.6",
    "codefog/contao-widget_tree_picker": ">=1.0.5"
},
"conflict": {
    "codefog/contao-widget_tree_picker": "2.0.0"
}
```

https://getcomposer.org/doc/04-schema.md#conflict

**Comment by fritzmg** [comment]
Ah right, forgot about `conflict` :). Yeah, then this issue is irrelevant (though hopefully still helpful for anyone who happens to come across this).

**Comment by Toflar** [comment]
:+1:
