### ISSUE TITLE
Error: Failed opening required '../../../initialize.php' (include_path='.:/usr/lib/php5.6') 

### ISSUE THREAD

**Issue by jenda77** [codefog/contao-widget_tree_picker#9]
Unfortunately, I get an error when I try to restrict the categories in a news archive. Can I resolve it by myself? Thank you. 

![bildschirmfoto 2015-08-13 um 12 31 55](https://cloud.githubusercontent.com/assets/3715050/9247918/742c11be-41b7-11e5-9195-e1248dee3343.png)
![bildschirmfoto 2015-08-13 um 12 32 02](https://cloud.githubusercontent.com/assets/3715050/9247923/7e57f824-41b7-11e5-9ac5-d85b61ccbaa2.png)

Fatal error: require_once(): Failed opening required '../../../initialize.php' (include_path='.:/usr/lib/php5.6') in /homepages/18/d42828063/htdocs/subdomains/babymanufactur/composer/vendor/contao-legacy/widget_tree_picker/TL_ROOT/system/modules/widget_tree_picker/public/treepicker.php on line 26

**Comment by qzminski** [comment]
Note to myself: use Isotope fix (https://github.com/isotope/core/blob/master/system/modules/isotope/postsale.php#L41).

**Comment by qzminski** [comment]
Can you try to use the latest hotfix branch and see if the error still appears?

https://github.com/codefog/contao-widget_tree_picker/tree/hotfix/2.0.2

**Comment by jenda77** [comment]
After de- and installation all of my modules it works. Maybe it is necessary to install it in a concrete order?

**Comment by qzminski** [comment]
Have you tried the hotfix branch or not?

**Comment by jenda77** [comment]
No, because I cannot install it when your extension news_categories requests the 2.0.1 version... 
![bildschirmfoto 2015-08-13 um 13 50 25](https://cloud.githubusercontent.com/assets/3715050/9249112/66533ada-41c2-11e5-9dfd-c4edd8ca43bd.png)

**Comment by jenda77** [comment]
But, it works for me with the 2.0.1 now.

**Comment by tristanlins** [comment]
This is still broken with dev-hotfix/2.0.2 (02b30567)

**Comment by tristanlins** [comment]
This is the correct snippet: `require_once '../../../../../system/initialize.php';`

**Comment by qzminski** [comment]
@tristanlins can you confirm it's ok now?

**Comment by tristanlins** [comment]
With the path from https://github.com/codefog/contao-widget_tree_picker/issues/9#issuecomment-155064047 it works :-)

**Comment by qzminski** [comment]
Thanks! I've just released 2.0.2 :+1:
